version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn HorizonGlow.wsgi:application -c gunicorn_config.py
    volumes:
      - .:/usr/src/app/
      - product_files:/usr/src/app/product_files
    ports:
      - "443:443"
      - "80:80"
    env_file:
      - ./.env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - "54432:5432"
    expose:
      - 5432
    env_file:
      - ./.env.prod
    volumes:
      - pg_data:/var/lib/postgresql/data/

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

  tg_bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/app/bot
    env_file:
      - ./bot/.env
    depends_on:
      - postgres

volumes:
  pg_data:
  product_files:
