version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn HorizonGlow.wsgi:application --bind 0.0.0.0:80 --access-logfile - --error-logfile - --log-level info
    volumes:
      - .:/usr/src/app/
    ports:
      - "80:80"
    env_file:
      - ./.env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - "54432:5432"
    expose:
      - 5432
    env_file:
      - ./.env.prod
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
