version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - product_files:/usr/src/app/product_files
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - "54432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
  product_files:
