# Generated by Django 5.1.2 on 2025-07-01 13:18

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('default', 'Default'), ('feedback', 'Feedback')], default='default', max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=news.models.Article.get_image_path, verbose_name='Attached image'),
        ),
    ]
