# Generated by Django 5.1.2 on 2024-12-29 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_user_is_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total earned')),
                ('to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='To pay')),
            ],
        ),
    ]
