general:
  error: "❌  An internal error has occured"

user_commands:
  start_message: "Hi, it's Horizon Glow Support Bot"
  new_ticket_button: "Contact support"
  new_ticket_answer: "Send us the Support Code of the product.\n\nYou can find it on Purchases page on https://horizon-glow.com/purchases after the description of the product.\n\nExample: #H07B"

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    file:
      format: '[%(asctime)s %(levelname)s] [%(name)s] %(message)s'
    console:
      format: '[%(levelname)s] [%(name)s] %(message)s'
  handlers:
    console:
      level: 'DEBUG'
      formatter: 'console'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
    file:
      level: 'DEBUG'
      formatter: 'file'
      class: 'logging.handlers.TimedRotatingFileHandler'
      filename: 'logs/log.log'
      when: 'midnight'
      backupCount: 6
      encoding: "utf-8"

  root:
    handlers: [ 'console', 'file' ]
    level: 'DEBUG'

  loggers:
    aiogram.event:
      handlers: [ 'console', 'file' ]
      level: 'WARNING'
      propagate: false
