
general:
  error: "❌  An internal error has occured"

user_commands:
  start_message: "Hi, it's Miami Cash Support Bot."
  start_message_image: "https://miami-cash.com/static/img/bot_start_image.jpg"
  instructions_message: "
<b>1. Product support</b>\n
\n
This section can be used ONLY for question is about the purchased product.\n
After payment, each product is assigned a unique code valid for 24 hours. You can find the code on Purchases page on https://miami-cash.com/purchases.\n
Describe your question, you can attach a photo or video confirmation of the problem.\n
Please be polite, support will answer you as soon as he can.\n
The product code works 24 hours from the moment of purchase.\n
Support does not teach, and all non-product-specific questions will be ignored.\n
\n
\n
<b>2. Custom order</b>\n
\n
This section can be used ONLY for a custom order.\n
Click the buttom CUSTOM ORDER.\n
Describe your request.\n
Support will review your request and if our team can handle the order, we will respond to you about the terms of the order.\n
Please be polite, support will answer you as soon as he can.\n
Support doesn't teach."

  message_no_ticket: "You should create a ticket to send messages to our Support Team. Use keyboard button on the bottom to create a new ticket."

  new_ticket:
    button_product: "Product support"
    button_custom: "Custom order"
    answer_product: "Send us the Support Code of the product or press the button below if your question is not related to an already bought product.\n\nYou can find the code on Purchases page on https://miami-cash.com/purchases after the description of the product.\n\nExample: <code>#H07B</code>"
    answer_custom: "Describe your request.\nSupport will review your request and if our team can handle the order, we will respond to you about the terms of the order."
    invalid_code: "Invalid support code. Please, check it and send the correct one."
    preriod_expired: "Support period of a product is 1 day. Sorry but you can't create a ticket for this product since the period has expired.\n\nYou can create a ticket without code. Click \"Create ticket\" below."
    already_have: "You already have an active ticket. Please close it before opening a new one."
    success_product: "Ticket was successfully created.\nProduct: {product_description}\n\nPlease describe your problem. All messages below will be sent to the support team.\nUse keyboard button on the bottom to close the ticket."
    success_custom: "Ticket was successfully created.\nAll messages below will be sent to the support team.\nUse keyboard button on the bottom to close the ticket."

  ticket:
    close_button: "Close ticket"

  close_ticket:
    closed_message: "Your ticket was closed.\n\nYou can create a new one via keyboard button on the bottom."

support_commands:
  ticket_is_closed: "This ticket is already closed"
  close_ticket_button: "Close ticket"

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    file:
      format: '[%(asctime)s %(levelname)s] [%(name)s] %(message)s'
    console:
      format: '[%(levelname)s] [%(name)s] %(message)s'
  handlers:
    console:
      level: 'DEBUG'
      formatter: 'console'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
    file:
      level: 'DEBUG'
      formatter: 'file'
      class: 'logging.handlers.TimedRotatingFileHandler'
      filename: 'logs/log.log'
      when: 'midnight'
      backupCount: 6
      encoding: "utf-8"

  root:
    handlers: [ 'console', 'file' ]
    level: 'DEBUG'

  loggers:
    aiogram.event:
      handlers: [ 'console', 'file' ]
      level: 'WARNING'
      propagate: false
    httpcore.http11:
      handlers: []
      level: "WARNING"
    httpcore.connection:
      handlers: [ ]
      level: "WARNING"
