"""add index to Ticket.topic_id

Revision ID: 0990a605ff0b
Revises: c953fc9d569f
Create Date: 2025-01-25 18:04:18.064821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0990a605ff0b'
down_revision: Union[str, None] = 'c953fc9d569f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tickets_topic_id'), 'tickets', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_topic_id'), table_name='tickets')
    # ### end Alembic commands ###
