"""added index to User.ticket

Revision ID: 8cf23f72f5f7
Revises: 0990a605ff0b
Create Date: 2025-01-26 01:34:51.108498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf23f72f5f7'
down_revision: Union[str, None] = '0990a605ff0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_ticket'), 'users', ['ticket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ticket'), table_name='users')
    # ### end Alembic commands ###
