# Generated by Django 5.1.2 on 2024-12-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmodel',
            options={'verbose_name': 'Content'},
        ),
    ]
