# Generated by Django 5.1.2 on 2024-12-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('download_all_products', 'Can download file of any product')]},
        ),
    ]
