# Generated by Django 5.1.2 on 2024-12-12 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['purchased_by'], name='products_pr_purchas_253410_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('file__isnull', False), models.Q(('file', ''), _negated=True)), fields=['-purchased_at'], name='file_not_null_not_empty_idx'),
        ),
    ]
