# Generated by Django 5.1.2 on 2025-01-05 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_products_pr_seller__1bcc9b_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_seller__1bcc9b_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'purchased_by', '-added_at'], name='products_pr_seller__98aab5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'purchased_by', '-purchased_at'], name='products_pr_seller__0bda34_idx'),
        ),
    ]
