# Generated by Django 5.1.2 on 2025-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_products_pr_seller__1bcc9b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_url',
            field=models.URLField(default=''),
        ),
    ]
