# Generated by Django 5.1.2 on 2025-01-15 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_description_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='support_code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['support_code', '-purchased_at'], name='products_pr_support_8e2ac7_idx'),
        ),
    ]
