# Generated by Django 5.1.2 on 2025-01-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_support_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('download_all_products', 'Can download file of any product'), ('read_support_info', 'Can read more product info')]},
        ),
    ]
