# Generated by Django 5.1.2 on 2025-02-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering_value',
            field=models.SmallIntegerField(default=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
