# Generated by Django 5.1.2 on 2025-02-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_ordering_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(max_length=9),
        ),
    ]
