# Generated by Django 5.1.2 on 2025-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(max_length=9, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.CharField(max_length=2, verbose_name='State'),
        ),
    ]
