# Generated by Django 5.1.2 on 2025-06-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_number_alter_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_service',
            field=models.BooleanField(default=False, help_text='Should products in this category be displayed and processed as services', verbose_name='For services'),
        ),
    ]
